// Textos de la terminal y del Incident Lab
export const STRINGS = {
  es: {
    helpTitle: "Comandos disponibles",
    help: [
      ["help", "esta ayuda"],
      ["whoami", "quién soy"],
      ["about", "sobre mí"],
      ["now", "en qué estoy ahora"],
      ["experience", "experiencia laboral"],
      ["skills", "habilidades"],
      ["metrics", "números"],
      ["cases", "casos de troubleshooting"],
      ["open <n>", "abrir un caso"],
      ["lab", "listar incidentes jugables"],
      ["play <n>", "resolver un incidente real"],
      ["cv [enfoque]", "CV (devsecops | plataforma | datos)"],
      ["contact", "cómo contactarme"],
      ["neofetch", "info del sistema"],
      ["theme", "cambiar tema claro/oscuro"],
      ["lang", "switch to English"],
      ["security", "reporte DevSecOps del sitio"],
      ["clear", "limpiar la pantalla"],
    ] as [string, string][],
    homeIntro: "Escribí `help` para ver comandos o `play` para resolver un incidente real de producción.",
    labWelcome: "Bienvenido al Incident Lab: incidentes reales de producción, en tu terminal.",
    casesHeader: "Casos publicados:",
    casesFooter: "Usá `open <n>` para leer uno.",
    labHeader: "Incidentes disponibles:",
    labFooter: "Usá `play <n>` para empezar. Dificultad: ★☆☆ a ★★★.",
    solved: "resuelto",
    openUsage: "Uso: open <n> (mirá la lista con `cases`).",
    playUsage: "Uso: play <n> (mirá la lista con `lab`).",
    opening: "Abriendo",
    noSuchFile: "no existe el archivo",
    noSuchDir: "no existe el directorio",
    notFound: "comando no encontrado",
    tryHelp: "Probá `help`.",
    themeNow: "Tema:",
    uptimeTail: "1 usuario, load average: café",
    sudo: "Buen intento. Este incidente no se resuelve con privilegios 😉",
    rm: "rm: operación denegada. Acá no se borra producción.",
    exit: "No hay escapatoria: probá `play` 😄",
    ocOutsideLab: "No estás conectado a ningún cluster. Entrá a uno con `play`.",
    editor: "Para salir de vim: Esc, :q! … mejor quedate en la terminal.",
    since: "desde",
    nfRole: "Rol",
    nfLocation: "Ubicación",
    nfUptime: "Uptime",
    nfStack: "Stack",
    nfFocus: "Foco",
    nfBuild: "Build",
    gameHelp: "Investigá con comandos (oc, df, ls, stat…). `hint` da una pista, `status` muestra tu progreso, `answer` para responder, `exit` para salir.",
    trySuggestion: "Podés empezar con:",
    suggestionsTitle: "Comandos útiles",
    newClue: "Nueva evidencia encontrada",
    readyToAnswer: "Ya tenés bastante evidencia. Escribí `answer` cuando quieras.",
    noUsefulOutput: "(el comando no aporta nada útil acá; probá otro ángulo o `hint`)",
    statusClues: "Evidencias",
    statusCommands: "Comandos",
    statusHints: "Pistas usadas",
    answerHow: "Respondé con el número (por ejemplo: 2).",
    answerInvalid: "Opción inválida. Respondé con el número de la opción.",
    wrong: "No es eso. Te dejo una pista:",
    correct: "¡Correcto! Incidente resuelto.",
    score: "Puntaje",
    readFullCase: "Leer el caso completo",
    afterSolve: "Escribí `lab` para jugar otro.",
    leftGame: "Saliste del incidente. Escribí `lab` para elegir otro.",
  },
  en: {
    helpTitle: "Available commands",
    help: [
      ["help", "this help"],
      ["whoami", "who I am"],
      ["about", "about me"],
      ["now", "what I'm doing now"],
      ["experience", "work experience"],
      ["skills", "skills"],
      ["metrics", "numbers"],
      ["cases", "troubleshooting case studies"],
      ["open <n>", "open a case study"],
      ["lab", "list playable incidents"],
      ["play <n>", "solve a real incident"],
      ["cv [focus]", "résumé (devsecops | platform | data)"],
      ["contact", "how to reach me"],
      ["neofetch", "system info"],
      ["theme", "toggle light/dark theme"],
      ["lang", "cambiar a español"],
      ["security", "site DevSecOps report"],
      ["clear", "clear the screen"],
    ] as [string, string][],
    homeIntro: "Type `help` to list commands or `play` to solve a real production incident.",
    labWelcome: "Welcome to the Incident Lab: real production incidents, in your terminal.",
    casesHeader: "Published case studies:",
    casesFooter: "Use `open <n>` to read one.",
    labHeader: "Available incidents:",
    labFooter: "Use `play <n>` to start. Difficulty: ★☆☆ to ★★★.",
    solved: "solved",
    openUsage: "Usage: open <n> (see the list with `cases`).",
    playUsage: "Usage: play <n> (see the list with `lab`).",
    opening: "Opening",
    noSuchFile: "no such file",
    noSuchDir: "no such directory",
    notFound: "command not found",
    tryHelp: "Try `help`.",
    themeNow: "Theme:",
    uptimeTail: "1 user, load average: coffee",
    sudo: "Nice try. This incident won't be solved with privileges 😉",
    rm: "rm: operation denied. We don't delete production here.",
    exit: "There's no escape: try `play` 😄",
    ocOutsideLab: "You're not connected to any cluster. Join one with `play`.",
    editor: "To exit vim: Esc, :q! … better stay in the terminal.",
    since: "since",
    nfRole: "Role",
    nfLocation: "Location",
    nfUptime: "Uptime",
    nfStack: "Stack",
    nfFocus: "Focus",
    nfBuild: "Build",
    gameHelp: "Investigate with commands (oc, df, ls, stat…). `hint` gives a clue, `status` shows progress, `answer` to answer, `exit` to quit.",
    trySuggestion: "You can start with:",
    suggestionsTitle: "Useful commands",
    newClue: "New evidence found",
    readyToAnswer: "You have enough evidence. Type `answer` whenever you're ready.",
    noUsefulOutput: "(that command doesn't tell you much here; try another angle or `hint`)",
    statusClues: "Evidence",
    statusCommands: "Commands",
    statusHints: "Hints used",
    answerHow: "Answer with the number (e.g. 2).",
    answerInvalid: "Invalid option. Answer with the option number.",
    wrong: "Not quite. Here's a hint:",
    correct: "Correct! Incident resolved.",
    score: "Score",
    readFullCase: "Read the full case study",
    afterSolve: "Type `lab` to play another one.",
    leftGame: "You left the incident. Type `lab` to pick another.",
  },
}

export type TerminalStrings = (typeof STRINGS)["es"]
